# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'appunca' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for appunca

  target 'appunca-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'appuncaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

